Add NengoEdge product page and "Related produts" section
abr/abr.github.io pull request #76
Opened 2022-05-31 13:08 UTC by drasmuss

2022-05-31 19:50 UTC, tbekolay requested changes
New product page LGTM, made some inline comments and we might want to get someone (Chris?) to look at the copy (either before or after merging).

The Related Products section isn't what I had envisioned. If you go to some product pages like [the Nengo one](https://appliedbrainresearch.com/products/nengo/), when you scroll under the product there's a "Services" section that advertises related services. I was envisioning a "Related products" block probably before the "Services" section that looks the same, but lists products instead of services, and including the pitch instead of just the name.

Arguably we could also remove the research sections, where they exist, as it's not really relevant at this point, and with a related products section the "Explore more products" at the bottom could be removed.

But yeah, not saying what I envisioned has to be what happens in the end. There's definitely an argument for having it above the fold, as they say, but I think having the pitch instead of just the title is probably important.

2022-05-31 19:50 UTC, tbekolay commented on _products/nengoedge.md
> +    Reduce product development time and hardware lock-in by taking advantage of the
maybe add "Reduce product development time and eliminate hardware lock-in..." ?

2022-05-31 19:50 UTC, tbekolay commented on _products/nengoedge.md
> +NengoEdge uses [Legendre Memory Units (LMUs)](/products/lmu), a proprietary recurrent neural network
The link here should be to `{{ site.baseurl }}{% link _products/lmu.md %}` ... only makes a difference if we change how files map to URLs but if we do it will reduce the amount of broken internal links.

2022-05-31 19:50 UTC, tbekolay commented on _products/nengoedge.md
> +NengoEdge uses [Legendre Memory Units (LMUs)](/products/lmu), a proprietary recurrent neural network
It is annoying to remember every time though so I do wonder if we should switch all the other links to being simple ones like this instead, I forget the source of that original pattern but I'm sure there was some reason for it.

2022-05-31 19:50 UTC, tbekolay commented on _products/nengoedge.md
> +Visit [https://edge.nengo.ai](https://edge.nengo.ai) to sign up for the beta!
Can simplify this as `<https://edge.nengo.ai>, it achieves the same result. However, I find it somewhat nicer to do `[edge.nengo.ai](https://edge.nengo.ai)` instead (no one cares to see the `https://`

2022-06-01 12:45 UTC, drasmuss commented on _products/nengoedge.md
> +    Reduce product development time and hardware lock-in by taking advantage of the
When rereading it, hardware lock-in seemed like it wasn't a major enough point that we want to really emphasize it in our high-level pitch, so I changed it to "development time and cost by taking advantage..."

2022-06-01 17:21 UTC, drasmuss commented
Fixups done, I moved the "Related products" to a block at the bottom as you suggested, since I didn't have a strong preference. One thing I wasn't sure of is whether we wanted it to come before or after the related Services (currently it's before).

2022-06-07 14:51 UTC, tbekolay approved these changes
All LGTM! I'm going to add a `beta` badge to the Products dropdown for NengoEdge and merge.

2022-06-07 14:54 UTC, merged